service: demoroyal
app: demoroyal-app
org: jvictor166

provider:
  name: aws
  runtime: nodejs12.x

package:
 individually: true
 excludeDevDependencies: false
 exclude:
   - 'src/**'
   - .DS_Store
   - build/**
   - tmp/**
   - .git/**
   - package-lock.json
   - 'tempv/**'
 include:
   - node_modules/**


functions:

# 01. servicio de prueba
  hello:
    handler: src/DEMO/handler.hello
    package:
      include:
        - 'src/DEMO/**'

# 02. obtener modelo Swapi
  getDataModelSwapi:
    handler: src/LMBROY001DATASWAPIGET002/handlerGet.get
    name: LMBROY001DATASWAPIGET002
    description: Lambda de prueba.
    package:
      include:
        - 'src/LMBROY001DATASWAPIGET002/**'
  