service: demoroyal
app: demoroyal-app
org: jvictor166

provider:
  name: aws
  runtime: nodejs12.x

package:
 individually: true
 excludeDevDependencies: false
 exclude:
   - 'src/**'
   - .DS_Store
   - build/**
   - tmp/**
   - .git/**
   - package-lock.json
   - 'tempv/**'
 include:
   - node_modules/**


functions:

# 01. servicio de prueba
  # hello:
  #   handler: src/DEMO/handler.hello
  #   package:
  #     include:
  #       - 'src/DEMO/**'

# 02. obtener modelo Swapi
  getDataModelSwapi:
    handler: src/LMBROY001DATASWAPIGET002/handlerGet.get
    name: LMBROY001DATASWAPIGET002
    description: Lambda de prueba.
    package:
      include:
        - 'src/LMBROY001DATASWAPIGET002/**'
    events:
      - http:
          path: model
          method: get
          integration: lambda
          cors:
            origin: '*'
            headers:
              - Content-Type
              # - X-Amz-Date
              # - Authorization
              # - X-Api-Key
              # - X-Amz-Security-Token
              # - X-Amz-User-Agent
              # - Access-Control-Allow-Origin
              # - Access-Control-Allow-Credentials
              # - User
          private: true
          request:
            passThrough: WHEN_NO_TEMPLATES
            parameters:
              querystrings:
                resource: false
                id: false
                search: false
            template:
              application/json: |-
                    #set($inputRoot = $input.path('$'))
                    {
                        "resource": "$input.params('resource')",
                        "id": "$input.params('id')",
                        "search": "$input.params('search')"
                    }


# 02. obtener modelo personalizado de la BD
  getDataCustom:
    handler: src/LMBROY001DATABASEGET003/handlerGet.get
    name: LMBROY001DATABASEGET003
    description: Lambda de prueba.
    package:
      include:
        - 'src/LMBROY001DATABASEGET003/**'
    events:
      - http:
          path: custommodel
          method: get
          integration: lambda
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials
              - User
          private: true
          request:
            passThrough: WHEN_NO_TEMPLATES
            parameters:
              querystrings:
                resource: false
            template:
              application/json: |-
                    #set($inputRoot = $input.path('$'))
                    {
                        "resource": "$input.params('resource')"
                    }
                    
                    
# 03. xxx     
